---
version: "3.8"

services:
  app:
    container_name: optom-letters
    image: optom-letters:latest
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - ../../.env
    restart: unless-stopped
    volumes:
      - ../..:/code/
    ports:
      - "${APP_PORT:-8999}:8000"
