---
version: "3.8"

services:
  app:
    container_name: optom-letters
    image: optom-letters:latest
    build:
      context: ../..
      dockerfile: ./docker/prod/Dockerfile
    env_file:
      - ../../.env
    restart: unless-stopped
    volumes:
      - ../..:/code/
    ports:
      - "${APP_PORT:-8888}:8000"
    command:
      - sh
      - -c
      - |
        gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80
